msg91.settings:
  label: 'MSG91 SMS Settings'
  type: config_object
  mapping:
    msg91_authKey:
      type: string
      label: 'MSG91 Authentication Key'
    msg91_senderID:
      type: string
      label: 'MSG91 Sender ID'
    msg91_route:
      type: integer
      label: 'MSG91 SMS Route'
